    name: GitHub Classroom Workflow

    on: 
      push: 
        paths: 
          # Do not run workflow unless these files were modified
          - 'laboratorio.py' 
          - 'test_laboratorio.py' 

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: education/autograding@v1